### PR TITLE
Adapt w.r.t. coq/coq#16004.

### PR DESCRIPTION
**Pull request by ppedrot**

### CODE REVIEW

**Comment by liyishuai** [comment]
Is there a way to make it backward compatible?

**Comment by ppedrot** [comment]
Up to which version do you want it to be compatible? In theory the current patch should be compatible up to 8.14, I don't know why the CI failed. With a few tweaks it can be made compatible up to 8.11.

**Comment by liyishuai** [comment]
All dependants of this library (per OPAM) currently develop on Coq >= 8.11, so it's fine to drop support to older Coq versions.

**Comment by ppedrot** [comment]
@liyishuai this should be backwards compatible up to 8.11 now.

**Comment by ppedrot** [comment]
@liyishuai ping

**Comment by liyishuai** [comment]
Cherry-picking 27022dbb6486f2ed802f292cededd001cbac0851 should fix the CI.

**Pull request merged**
