### PR TITLE
adapt to coq/coq#19872

### PR DESCRIPTION
**Pull request by liyishuai**

### CODE REVIEW

**Comment by SkySkimmer** [comment]
What's going on in the CI?

**Comment by liyishuai** [comment]
Should be fixed after coq-community/docker-base#29. Restarting.

**Comment by liyishuai** [comment]
I can't replicate this issue on macOS. @Lysxia any idea where the problem is?

**Comment by SkySkimmer** [comment]
almost green but 8.17 still red

**Comment by liyishuai** [comment]
- [ ] coq/opam#3231

**Pull request merged**
