### PR TITLE
Use replace instead of cutrewrite.

### PR DESCRIPTION
**Pull request by Zimmi48**
Compatibility with coq/coq#12993.

### CODE REVIEW

**Comment by Zimmi48** [comment]
The 8.12 test failed during the coqdoc build step with:

```
File "./theories/Data/Option.v", line 183, characters 0-34:
Warning: Removed file ./theories/Data/Option.vo
Error: Anomaly "Uncaught exception End_of_file."
Please report at http://coq.inria.fr/bugs/.

File "./theories/Data/Option.v", line 183, characters 0-34:
Warning: Removed file ./theories/Data/Option.vo
Error: System error: "./theories/Data/Option.vo: No such file or directory"
```

@liyishuai Have you seen this before?

**Review by liyishuai — APPROVED** [review]
The CI failure is nondeterministic. Restarting.

**Comment by Zimmi48** [comment]
Ah, we restarted it at the same time it seems.

**Comment by Zimmi48** [comment]
The second run also led to the non-deterministic failure. Maybe the third will be the good one?

BTW is this something that should be reported as an issue to Coq?

**Comment by Zimmi48** [comment]
Nope. I've tried a fourth time.

**Comment by Zimmi48** [comment]
OK this time it looks like it is going to pass.

**Comment by liyishuai** [comment]
Found a similar issue with Coqdoc: https://sympa.inria.fr/sympa/arc/coq-club/2014-03/msg00039.html
Not sure if parallel compilation caused this failure.

**Comment by Zimmi48** [comment]
OK, if that's the same error, it doesn't look very new. I was worried to see it happen 3 times in a row but on 8.12 only that this could be some problem that would have been introduced recently. Anyway, that might still be worth to report if you wish.

**Pull request merged**
