### PR TITLE
Add Hint Mode to Functor, Applicative, Monad

### PR DESCRIPTION
**Pull request by Lysxia**
Not sure why the definition of `sequence` breaks...

### CODE REVIEW

**Comment by liyishuai** [comment]
Now ITree is broken 🙃

**Comment by liyishuai** [comment]
Breaks `MonadLaws` on Coq 8.8~8.11; breaks ITree on Coq 8.12~8.15. Any fix for `MonadLaws`?

**Comment by Lysxia** [comment]
coq-itree 4.0.0 is broken but dev is fixed.

**Comment by Lysxia** [comment]
And I can't reproduce the weird CI failure on 8.9

**Comment by liyishuai** [comment]
Any idea with the CertiCoq breakage?

**Comment by Lysxia** [comment]
To be fixed in https://github.com/CertiCoq/certicoq/pull/86

**Review by liyishuai — APPROVED** [review]

**Comment by Lysxia** [comment]
For reference I asked about this practice of `Hint Mode` [on Zulip](https://coq.zulipchat.com/#narrow/stream/237977-Coq-users/topic/Hint.20Mode.20on.20type.20classes.2C.20best.20practice.3F), and learned that this is common practice in stdpp and iris.

**Comment by liyishuai** [comment]
Schedule:
1. [ ] coq/opam#2893
2. Merge and release a new version of ExtLib
3. [ ] coq/opam#2894

**Pull request merged**
