### PR TITLE
Replace use of omega with lia for Coq 8.14 #13741

### PR DESCRIPTION
**Pull request by jfehrle**
For https://github.com/coq/coq/pull/13741

### CODE REVIEW

**Review by liyishuai — APPROVED** [review]

**Comment by jfehrle** [comment]
The checks are still not complete after 12+ hours.  They all look like this:

image

Is some human intervention needed?

**Comment by liyishuai** [comment]
Seems like CircleCI wasn't enabled on your fork.

**Comment by liyishuai** [comment]
Tests passed on my fork; merged.

**Comment by jfehrle** [comment]
Thanks for your help.  I   had 2 jobs fail in the coqdoc stage with different errors.  I guess those were transient errors?

Example:

```
Error:
/home/coq/project/theories/Data/HList.vo: premature end of file. Try to rebuild it
```

**Comment by liyishuai** [comment]
Those errors happen occasionally, and usually turn green upon rerun.

**Pull request merged**
