### PR TITLE
Applicative is Functor

### PR DESCRIPTION
**Pull request by liyishuai**
Help needed:
- [ ] Instance "PApplicative is PFunctor"

### CODE REVIEW

**Comment by gmalecha** [comment]
I don't know how useful people find the P-versions of things. Does it make sense to just remove them? What we do with them can be accomplished via dependent types at some computation cost.

**Comment by liyishuai** [comment]
I haven't used them yet. We can remove them if that doesn't break any dependant (CI can tell that).

**Comment by gmalecha** [comment]
I think this is a good way to go.

I also wonder if there would be interest from the community to pull out Monad, Functor, Applicative as a separate library. There are a lot of libraries with exactly the same definitions and it is kind of annoying to have the same code in multiple dependencies because they don't interoperate. Specifically, I am thinking about stdpp, extlib, and meta-coq, but I wouldn't be surprised if there are others.

**Comment by vzaliva** [comment]
I support the idea of pulling monads into a separate package. It should be lean and minimalistic so it could be easily combined with other libraries.

**Comment by liyishuai** [comment]
Should we start another repo for that monad package?

**Comment by gmalecha** [comment]
I think so. I think it deserves a bit of thought though as we would like a light weight solution that is still sufficient to do almost everything that people already do.

I think it is also important to find who has existing implementations of this functionality and what would get them to switch to a dependency.

**Comment by vzaliva** [comment]
My original suggestion:

I have seen many projects putting together their own Monad stuff in Coq. Sometimes poorly. Ideally, they should all use ExtLib, but I think it has more than people really need and they are hesitant to bring another foundation library as a dependency.

Have you thought about breaking down ExtLib and moving Mondas into a separate small library? Call it something 'coq-monads' so people can easily find it. I think that will lower down the barrier to entry and many more projects will adopt it. How knows, this could be a "gateway drug" to use the rest of ExtLib later :)

Comment from @gmalecha (https://github.com/coq-community/coq-ext-lib/pull/77 : 

I also wonder if there would be interest from the community to pull out Monad, Functor, Applicative as a separate library. There are a lot of libraries with exactly the same definitions and it is kind of annoying to have the same code in multiple dependencies because they don't interoperate. Specifically, I am thinking about stdpp, extlib, and meta-coq, but I wouldn't be surprised if there are others.

**Comment by liyishuai** [comment]
Discussions are continued in #79

**Pull request merged**
